/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import backend.Computer;
import backend.Memory;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import java.util.Vector;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mateusmesturini
 */
public class tela extends javax.swing.JFrame {

    /**
     * Creates new form tela
     */
    public Memory memoria = new Memory(32);
    Computer mv = new Computer(memoria);
    int linhaTabSel = 0;
    javax.swing.Timer timer;
 
    
    
    public tela() {
        
        initComponents();
        opMode1.setSelected(true);
        filePath.setText("/Users/mateusmesturini/Dropbox/AULA/PS/TrabMaquinaVirtual/MaquinaVirtual/src/maquinavirtual/file.txt");
        
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        filePath = new javax.swing.JTextField();
        chooseFile = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        opMode1 = new javax.swing.JRadioButton();
        opMode2 = new javax.swing.JRadioButton();
        opMode3 = new javax.swing.JRadioButton();
        closeButton = new javax.swing.JButton();
        loadCode = new javax.swing.JButton();
        runButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("File path:");

        chooseFile.setText("...");
        chooseFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseFileActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "opcode", "op1", "op2", "end"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Registrador", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel2.setText("Modo de Operação");

        buttonGroup1.add(opMode1);
        opMode1.setText("Run complete machine");

        buttonGroup1.add(opMode2);
        opMode2.setText("Run slowly (1s per instruction)");

        buttonGroup1.add(opMode3);
        opMode3.setText("Run step-by-step (hit RUN for next)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(opMode2)
                    .addComponent(opMode1)
                    .addComponent(opMode3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opMode1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opMode2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opMode3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        closeButton.setText("Fechar");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        loadCode.setText("LOAD");
        loadCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadCodeActionPerformed(evt);
            }
        });

        runButton.setText("RUN");
        runButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(loadCode)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(runButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(filePath, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chooseFile))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(closeButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chooseFile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                        .addComponent(closeButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(loadCode)
                            .addComponent(runButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeButtonActionPerformed

    private void chooseFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseFileActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.showOpenDialog(null);
        File file = fileChooser.getSelectedFile();
        String filename = file.getAbsolutePath();
        filePath.setText(filename);
    }//GEN-LAST:event_chooseFileActionPerformed

    
    //atualiza a tabela do programa
    public void atualizarTabela(Memory memoria){
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        
        for(int i=0; memoria.size>i;){
            int mod1 = 0;
            int mod2 = 0;
            
            
            short opcode;
            opcode = memoria.load(i++);
  
                if (opcode > 31 && opcode < 128) {
				if (opcode > 97) {
					opcode -= 96;
					mod1 = 1;
					mod2 = 1;
				}
				else if (opcode > 63) {
					opcode -= 64;
                    mod1 = 1;
                    mod2 = 1;
                }
                else {
                    opcode -= 32;
                    mod1 = 1;
                }
            }
            else if (opcode > 128) {
                opcode -= 128;
                if (opcode == 13 || opcode == 45) {//copy
                    mod2 = 2;
                    if (opcode == 45) {
                        opcode -= 32;
                        mod1 = 1;
                    }
                }
                else {
                    mod1 = 2;
                }
            }
            System.out.println("opcde: " + opcode);
            switch(opcode) {
                case 0:
                    if (mod1 == 0) {
                        model.addRow(new Object[]{"BR", memoria.load(i++),"","DIR"});
                    }
                    else {
                        model.addRow(new Object[]{"BR", memoria.load(i++),"","IND"});
                    }
                    break;
                    
                case 1:
                    
                    if (mod1 == 0) {
                        model.addRow(new Object[]{"BRPOS", memoria.load(i++),"","DIR"});
                    }
                    else {
                        model.addRow(new Object[]{"BRPOS", memoria.load(i++),"","IND"});
                    }
                    break;
                    
                case 2:
                    
                    if (mod1 == 0) {
                        model.addRow(new Object[]{"ADD", memoria.load(i++),"","DIR"});
                    }
                    else if (mod1 == 1) {
                        model.addRow(new Object[]{"ADD", memoria.load(i++),"","IND"});
                    }
                    else {
                        model.addRow(new Object[]{"ADD", memoria.load(i++),"","IM"});
                    }
                    break;
                    
                case 3:
                    
                    if (mod1 == 0) {
                        model.addRow(new Object[]{"LOAD", memoria.load(i++),"","DIR"});
                    }
                    else if (mod1 == 1) {
                        model.addRow(new Object[]{"LOAD", memoria.load(i++),"","IND"});
                    }
                    else {
                        model.addRow(new Object[]{"LOAD", memoria.load(i++),"","IM"});
                    }
                    break;
                    
                case 4:
                    
                    if (mod1 == 0) {
                        model.addRow(new Object[]{"BRZERO", memoria.load(i++),"","DIR"});
                    }
                    else {
                        model.addRow(new Object[]{"BRZERO", memoria.load(i++),"","IND"});
                    }
                    break;
                    
                case 5:
                    
                    if (mod1 == 0) {
                        model.addRow(new Object[]{"BRNEG", memoria.load(i++),"","DIR"});
                    }
                    else {
                        model.addRow(new Object[]{"BRNEG", memoria.load(i++),"","IND"});
                    }
                    break;
                    
                case 6:
                    
                    if (mod1 == 0) {
                        model.addRow(new Object[]{"SUB", memoria.load(i++),"","DIR"});
                    }
                    else if (mod1 == 1) {
                        model.addRow(new Object[]{"SUB", memoria.load(i++),"","IND"});
                    }
                    else {
                        model.addRow(new Object[]{"SUB", memoria.load(i++),"","IM"});
                    }
                    break;
                    
				
		case 7:
                    
                    if (mod1 == 0) {
                        model.addRow(new Object[]{"STORE", memoria.load(i++),"","DIR"});
                    }
                    else {
                        model.addRow(new Object[]{"STORE", memoria.load(i++),"","IND"});
                    }
                    break;
				
				case 8:
                    
                    if (mod1 == 0) {
                        model.addRow(new Object[]{"WRITE", memoria.load(i++),"","DIR"});
                    }
                    else if (mod1 == 1) {
                        model.addRow(new Object[]{"WRITE", memoria.load(i++),"","IND"});
                    }
                    else {
                        model.addRow(new Object[]{"WRITE", memoria.load(i++),"","IM"});
                    }
                    break;
                    
					
		case 10:
                    
                    if (mod1 == 0) {
                        model.addRow(new Object[]{"DIVIDE", memoria.load(i++),"","DIR"});
                    }
                    else if (mod1 == 1) {
                        model.addRow(new Object[]{"DIVIDE", memoria.load(i++),"","IND"});
                    }
                    else {
                        model.addRow(new Object[]{"DIVIDE", memoria.load(i++),"","IM"});
                    }
                    break;
                    
                    //depois do STOP eh area de dados, ao le mais instrucoes
                case 11:
                    model.addRow(new Object[]{"STOP"});
                    while(i<memoria.size){
                        model.addRow(new Object[]{memoria.load(i++),"","",""}); //todos os valores apos stop sao dados                     
                    }
                    break;
				
		case 12:
                    
                    if (mod1 == 0) {
                        model.addRow(new Object[]{"READ", memoria.load(i++),"","DIR"});
                    }
                    else {
                        model.addRow(new Object[]{"READ", memoria.load(i++),"","IND"});
                    }
                    break;
				
		case 13:
                    
			 		
                    if (mod1 == 0 && mod2 == 0) {
                        model.addRow(new Object[]{"COPY", memoria.load(i++),memoria.load(i++),"DIR/DIR"});
                    }
                    else if (mod1 == 0 && mod2 == 1) {
                        model.addRow(new Object[]{"COPY", memoria.load(i++),memoria.load(i++),"DIR/IND"});
                    }
                    else if (mod1 == 0 && mod2 == 2) {
                        model.addRow(new Object[]{"COPY", memoria.load(i++),memoria.load(i++),"DIR/IM"});
                    }
                    if (mod1 == 1 && mod2 == 0) {
                        model.addRow(new Object[]{"COPY", memoria.load(i++),memoria.load(i++),"IND/DIR"});
                    }
                    else if (mod1 == 1 && mod2 == 1) {
                        model.addRow(new Object[]{"COPY", memoria.load(i++),memoria.load(i++),"IND/IND"});
                    }
                    else if (mod1 == 1 && mod2 == 2) {
                        model.addRow(new Object[]{"COPY", memoria.load(i++),memoria.load(i++),"IND/IM"});
                    }
                    break;
				
		case 14:
                    
                    if (mod1 == 0) {
                        model.addRow(new Object[]{"MULT", memoria.load(i++),"",memoria.load(i++),"DIR"});
                    }
                    else if (mod1 == 1) {
                        model.addRow(new Object[]{"MULT", memoria.load(i++),"",memoria.load(i++),"IND"});
                    }
                    else {
                        model.addRow(new Object[]{"MULT", memoria.load(i++),"",memoria.load(i++),"IM"});
                    }
                    break;
                    
				
		case 15:
                    
                    if (mod1 == 0) {
                        model.addRow(new Object[]{"CALL", memoria.load(i++),"","DIR"});
                    }
                    else {
                        model.addRow(new Object[]{"CALL", memoria.load(i++),"","IND"});
                    }
                    break;
					
                case 16:
                    model.addRow(new Object[]{"RET"});
                
            }
            
        
        }
        
        jTable1.setRowSelectionInterval(linhaTabSel, linhaTabSel);
        linhaTabSel++;
        System.out.println(linhaTabSel);
        
    }
    
    //atuzaliza tabela com registradores
    public void atualizarRegistradores(Computer mv){
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.setRowCount(0);
        
        model.addRow(new Object[]{"PC", mv.pc});
        model.addRow(new Object[]{"ACC", mv.acc});
        model.addRow(new Object[]{"RE", mv.re});
        model.addRow(new Object[]{"RI", mv.ri});
        if(mv.sp.empty()){model.addRow(new Object[]{"Stack", "empty"});}
        else{model.addRow(new Object[]{"Stack", mv.sp.peek()});}
        
        
    
    }
    
    private void loadCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadCodeActionPerformed
        linhaTabSel = 0;
        try {
            
            //carrega o arquivo na memoria
            Scanner scanner;
            scanner = new Scanner(new File(filePath.getText())); 
            int i = 0;
            while(scanner.hasNextShort()){
                memoria.store(scanner.nextShort(), i++);
            }
            
            //atualiza a tabela com a memoria
            mv.reset();
            atualizarTabela(memoria);
            mv.ri = mv.memoria.load(0); //gambiarra pra atualizar o valor RI
            atualizarRegistradores(mv);
            
            
            
            
            
            
          

        } catch (FileNotFoundException ex) {
            Logger.getLogger(tela.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        

    }//GEN-LAST:event_loadCodeActionPerformed

    private void runButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runButtonActionPerformed
        
        
        if(opMode1.isSelected()){
            while(mv.ri != 11){
                mv.run();
                atualizarRegistradores(mv);
                atualizarTabela(mv.memoria);
            }
        }
        
        if(opMode2.isSelected()){
            while(mv.ri != 11){
                mv.run();
                atualizarRegistradores(mv);
                atualizarTabela(mv.memoria);
              
                // precisa fazer um jeito para que ele demore um segundo entre cada operacao
            }
        }
        
        
        if(opMode3.isSelected()){
            if(mv.ri != 11){
                mv.run();
                atualizarRegistradores(mv);
                atualizarTabela(mv.memoria);
                             
            }else{
                
            }    
        }
        if(mv.ri == 11){
            JFrame frame = new JFrame();
            JOptionPane.showMessageDialog(frame,"DONE!");
        }
        
        
    }//GEN-LAST:event_runButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton chooseFile;
    private javax.swing.JButton closeButton;
    private javax.swing.JTextField filePath;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton loadCode;
    private javax.swing.JRadioButton opMode1;
    private javax.swing.JRadioButton opMode2;
    private javax.swing.JRadioButton opMode3;
    private javax.swing.JButton runButton;
    // End of variables declaration//GEN-END:variables
}
